version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/client-portal-runtime
    schedule:
      interval: weekly
    groups:
      runtime-dependencies:
        patterns: ['*']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /packages/client-portal-runtime/gateway
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /packages/client-portal-runtime/broker
    schedule:
      interval: weekly

